/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author USER
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel = new javax.swing.JPanel();
        Btchou = new javax.swing.JButton();
        Btgord = new javax.swing.JButton();
        Btvalir = new javax.swing.JButton();
        BtKeluar = new javax.swing.JButton();
        ImagePanel = new javax.swing.JPanel();
        Imgchou = new javax.swing.JLabel();
        Imgvalir = new javax.swing.JLabel();
        Imggord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnPanel.setBackground(new java.awt.Color(0, 0, 0));

        Btchou.setText("chou");
        Btchou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtchouActionPerformed(evt);
            }
        });
        BtnPanel.add(Btchou);

        Btgord.setText("gord");
        Btgord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtgordActionPerformed(evt);
            }
        });
        BtnPanel.add(Btgord);

        Btvalir.setText("valir");
        Btvalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtvalirActionPerformed(evt);
            }
        });
        BtnPanel.add(Btvalir);

        BtKeluar.setText("Keluar");
        BtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtKeluarActionPerformed(evt);
            }
        });
        BtnPanel.add(BtKeluar);

        getContentPane().add(BtnPanel, java.awt.BorderLayout.PAGE_START);

        ImagePanel.setBackground(new java.awt.Color(51, 51, 51));
        ImagePanel.setLayout(new java.awt.CardLayout());

        Imgchou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imgchou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/chou.jpg"))); // NOI18N
        ImagePanel.add(Imgchou, "0");

        Imgvalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imgvalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/valir.jpg"))); // NOI18N
        ImagePanel.add(Imgvalir, "2");

        Imggord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imggord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/gord.jpg"))); // NOI18N
        ImagePanel.add(Imggord, "1");

        getContentPane().add(ImagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtchouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtchouActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "0");
    }//GEN-LAST:event_BtchouActionPerformed

    private void BtgordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtgordActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "1");
    }//GEN-LAST:event_BtgordActionPerformed

    private void BtvalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtvalirActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "2");
    }//GEN-LAST:event_BtvalirActionPerformed

    private void BtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtKeluar;
    private javax.swing.JButton Btchou;
    private javax.swing.JButton Btgord;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JButton Btvalir;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel Imgchou;
    private javax.swing.JLabel Imggord;
    private javax.swing.JLabel Imgvalir;
    // End of variables declaration//GEN-END:variables
}
